name = "SummerMod"
author = "Nostal Yuu"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec2517e1ab5c859383c6e72c20b54db80a48ec32248bb86fd305bcd2295c537d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
