name = "SummerMod"
author = "Nostal Yuu"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f9f477ab192cb4f21dcc50a757a782f85695fa79b1eca54c2599fb4d06e61c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
