name = "SummerMod"
author = "Nostal Yuu"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa2319f6f4acc555dba3fd11e5cf8e2f7d415d46bf7a2ad1e802b1dd2648d7cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
